name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    container: jackiempty/aoc2026-env:latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build CPU Tests
        run: |
          echo "Building CPU kernels..."
          cd test/cpu
          make all
          ls -l elf/

      - name: Build DLA Tests
        run: |
          echo "Building DLA kernels..."
          cd test/dla
          make all -j
          ls -l dla*/*.elf

      - name: Run Autograding Tests
        uses: education/autograding@v1